name: VNC Server Remote
on: workflow_dispatch # Hanya berjalan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Desktop Environment and VNC
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tightvncserver dbus-x11
          
      - name: Setup VNC Password
        run: |
          mkdir -p ~/.vnc
          echo "${{ secrets.ikuk }}" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
      - name: Start VNC Server
        run: |
          vncserver -geometry 1280x800 -depth 24 :1
          
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok
          
      - name: Start Ngrok Tunnel
        run: |
          ngrok config add-authtoken ${{ secrets.3Aaj4xVMWxbxTXc1b7Vw3AyUo5O_MVaCvcGXg8GbzA9aNoSF }}
          ngrok tcp 5901 &
          
      - name: Get VNC Address
        run: |
          echo "Waiting for ngrok to start..."
          sleep 10
          curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
          
      - name: Keep Alive
        run: |
          echo "VNC Running... Press Ctrl+C to cancel if running locally."
          sleep 21600 # Menahan sesi selama 6 jam
